PNC\ChiroBundle\Entity\InfoSite:
    type: entity
    table: chiro.chiro_infos_site
    schema: chiro
    repositoryClass: PNC\ChiroBundle\Repositories\InfoSiteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        site_id:
            type: integer
        site_description:
            type: text
            nullable: true
        site_schema:
            type: string
            length: 255
            nullable: true
        site_frequentation:
            type: text
            nullable: true
        site_menace:
            type: text
            nullable: true
        site_amenagement:
            type: text
            nullable: true
        site_commentaire:
            type: text
            nullable: true
        contact_nom:
            type: string
            length: 25
            nullable: true
        contact_prenom:
            type: string
            length: 25
            nullable: true
        contact_adresse:
            type: string
            length: 150
            nullable: true
        contact_code_postal:
            type: string
            length: 5
            nullable: true
        contact_ville:
            type: string
            length: 100
            nullable: true
        contact_telephone:
            type: string
            length: 15
            nullable: true
        contact_portable:
            type: string
            length: 15
            nullable: true
        contact_commentaire:
            type: text
            nullable: true

    oneToOne:
        parent_site:
            targetEntity: PNC\BaseAppBundle\Entity\Site
            joinColumn:
                name: site_id
                referencedColumnName: id

