PNC\ChiroBundle\Entity\ObservationView:
    type: entity
    table: chiro.vue_chiro_obs
    schema: chiro
    repositoryClass: PNC\ChiroBundle\Repositories\ObservationView
    id:
        id:
            type: integer
            id: true
    fields:
        site_id:
            type: integer
        site_nom:
            type: text
        obs_date:
            type: date
        numerisateur_id:
            type: integer
        numerisateur:
            type: text
        obs_commentaire:
            type: text
        obs_id_table_src:
            type: integer
        obs_temperature:
            type: decimal
        obs_humidite:
            type: decimal
        nb_taxons:
            type: integer

    manyToMany:
        observateurs:
            targetEntity: PNC\ChiroBundle\Entity\ObservateurView
            joinTable:
                name: pnc.rel_obs_obr
                joinColumns:
                    obs_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    obr_id:
                        referencedColumnName: obr_id

