PNC\ChiroBundle\Entity\ObservationSsSiteView:
    type: entity
    table: chiro.vue_chiro_obs_ss_site
    schema: chiro
    id:
        id:
            type: integer
            id: true
    fields:
        geom:
            type: json_array
        obs_date:
            type: date
        numerisateur_id:
            type: integer
        numerisateur:
            type: text
        obs_commentaire:
            type: text
        obs_id_table_src:
            type: integer
        obs_temperature:
            type: float
        obs_humidite:
            type: float
        nb_taxons:
            type: integer
        abondance:
            type: integer

    manyToMany:
        observateurs:
            targetEntity: PNC\ChiroBundle\Entity\ObservateurView
            joinTable:
                name: pnc.rel_obs_obr
                joinColumns:
                    obs_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    obr_id:
                        referencedColumnName: obr_id
