#pnc_base_app_homepage:
#    path:     /hello/{name}
#    defaults: { _controller: PNCBaseAppBundle:Default:index }

pnc_observation_list:
    path:     /observation
    defaults: { _controller: PNCBaseAppBundle:Observation:list }
    requirements:
        _method: GET

pnc_observation_detail:
    path:     /observation/{id}
    defaults: { _controller: PNCBaseAppBundle:Observation:detail }
    requirements:
        _method: GET

pnc_observation_save:
    path:     /observation/{id}
    defaults: { _controller: PNCBaseAppBundle:Observation:save, id: null }
    requirements:
        _method: POST

pnc_observation_suppr:
    path:     /observation/{id}
    defaults: { _controller: PNCBaseAppBundle:Observation:delete }
    requirements:
        _method: DELETE



pnc_site_list:
    path:     /site
    defaults: { _controller: PNCBaseAppBundle:Site:list }
    requirements:
        _method: GET

pnc_site_detail:
    path:     /site/{id}
    defaults: { _controller: PNCBaseAppBundle:Site:detail, id: null }
    requirements:
        _method: GET

pnc_site_save:
    path:     /site/{id}
    defaults: { _controller: PNCBaseAppBundle:Site:save }
    requirements:
        _method: POST

pnc_site_suppr:
    path:     /site/{id}
    defaults: { _controller: PNCBaseAppBundle:Site:delete }
    requirements:
        _method: DELETE
