services:
#    pnc_base_app.example:
#        class: PNC\BaseAppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    baseSiteService:
        class: PNC\BaseAppBundle\Services\BaseSiteService
        arguments: [@geometry]
    baseObservationService:
        class: PNC\BaseAppBundle\Services\BaseObservationService
        arguments: [@geometry]

