PNC\PatrimoineBatiBundle\Entity\InfoSite:
    type: entity
    table: patrimoinebati.pr_site_infos
    schema: patrimoinebati
    #repositoryClass: PNC\PatrimoineBatiBundle\Repositories\InfoSiteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fk_bs_id:
            type: integer
        pb_des_code_ref:
            type: text
            nullable: true
        pb_des_denomination_locale:
            type: text
            nullable: true
        pb_des_nom_synononymes:
            type: text
            nullable: true
        pb_loc_lieudit:
            type: text
            nullable: true
        pb_loc_situation:
            type: integer
            nullable: true
        pb_loc_orientation:
            type: integer
            nullable: true
        pb_loc_visibilite:
            type: integer
            nullable: true
        pb_loc_accessibilite:
            type: integer
            nullable: true
        pb_loc_statut:
            type: integer
            nullable: true
        pb_his_datation_type:
            type: integer
            nullable: true
        pb_his_datation_periode:
            type: integer
            nullable: true
        pb_his_datation_exacte:
            type: text
            nullable: true
        pb_des_dimensions_larg:
            type: float
            nullable: true
        pb_des_dimensions_long:
            type: float
            nullable: true
        pb_des_dimensions_haut:
            type: float
            nullable: true
        pb_des_dimensions_e:
            type: float
            nullable: true
        pb_des_dimensions_d:
            type: float
            nullable: true
        pb_des_environnement_proche:
            type: text
            nullable: true
        pb_des_mur_grosoeuvre:
            type: integer
            nullable: true
        pb_des_mur_misenoeuvre:
            type: integer
            nullable: true
        pb_des_mur_misenoeuvre:
            type: integer
            nullable: true
        pb_des_mur_revetement:
            type: integer
            nullable: true
        pb_des_toit:
            type: integer
            nullable: true
        pb_des_toit_precision:
            type: text
            nullable: true
        pb_des_couvrement:
            type: integer
            nullable: true
        pb_des_baie:
            type: integer
            nullable: true
        pb_des_baie_precision:
            type: text
            nullable: true
        pb_des_baie_precision:
            type: text
            nullable: true
        pb_des_complementaire:
            type: text
            nullable: true
        pb_des_etat:
            type: integer
            nullable: true
        pb_interpretation:
            type: integer
            nullable: true
        pb_commentaire:
            type: text
            nullable: true
        pb_traitement_donnees:
            type: integer
            nullable: true
        pb_source:
            type: integer
            nullable: true
    oneToOne:
        parent_site:
            targetEntity: PNC\BaseAppBundle\Entity\Site
            joinColumn:
                name: fk_bs_id
                referencedColumnName: id
