-   id: 1
    name: Chiroptères
    base_url: "chiro/site"
    img: "img/chiro.png"
    menu:
        -   url: "#/chiro/site"
            label: "Suivi"
            restrict: 2
        -   url: "#/chiro/inventaire"
            label: "Inventaire"
            restrict: 2
        -   url: "#/chiro/validation"
            label: "Validation"
            restrict: 5
    appId: 100
#-   id: 2
#    name: flore
#    base_url: "flore/site"
#    appId: 20
#-   id: 3
#    name: eau
#    base_url: "eau/site"
#    appId: 40
#-   id: 4
#    name: cheveche
#    base_url: "cheveche/site"
#    appId: 110
