services:
#    pnc_chiro.example:
#        class: PNC\ChiroBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


    biometrieService:
        class: PNC\ChiroBundle\Services\BiometrieService
        arguments: [@doctrine, @normalizer]
            
    taxonService:
        class: PNC\ChiroBundle\Services\TaxonService
        arguments: [@doctrine, @normalizer, @biometrieService, @pagination]
            
    observationService:
        class: PNC\ChiroBundle\Services\ObservationService
        arguments: [@doctrine, @normalizer, @taxonService, @baseObservationService]
            
    siteService:
        class: PNC\ChiroBundle\Services\SiteService
        arguments: [@doctrine, @normalizer, @observationService, @baseSiteService]
            
